(function () {
    window.TRAVEL_DATA = {
        brand: {
            name: "Akatsuki Travel",
            tagline: "Modern travel planning for city breaks, resort stays, and curated escapes."
        },
        collections: [
            {
                id: "city",
                label: "City Escapes",
                eyebrow: "Fast-paced stays",
                description: "Rooftop hotels, quiet lofts, and central locations for short urban breaks."
            },
            {
                id: "coast",
                label: "Coastal Weekends",
                eyebrow: "Sea-view living",
                description: "Sunlit villas and boutique hotels for slower mornings by the water."
            },
            {
                id: "signature",
                label: "Signature Retreats",
                eyebrow: "Statement stays",
                description: "Design-led homes and high-touch hospitality for once-a-year trips."
            }
        ],
        destinations: [
            {
                id: "london",
                name: "London",
                region: "United Kingdom",
                priceFrom: 250,
                image: "images/image-1.png",
                description: "Design hotels, West End nights, and quick rail access across the city.",
                collection: "city"
            },
            {
                id: "switzerland",
                name: "Switzerland",
                region: "Alpine Europe",
                priceFrom: 320,
                image: "images/image-2.png",
                description: "Lakefront escapes and mountain-edge stays with clean modern interiors.",
                collection: "signature"
            },
            {
                id: "australia",
                name: "Australia",
                region: "Oceania",
                priceFrom: 410,
                image: "images/image-3.png",
                description: "Harbor city apartments, surf hotels, and long-haul bucket-list energy.",
                collection: "signature"
            },
            {
                id: "france",
                name: "France",
                region: "Western Europe",
                priceFrom: 290,
                image: "images/image-4.png",
                description: "From Parisian flats to Riviera hotels with a sharper 2026 visual edge.",
                collection: "city"
            },
            {
                id: "amsterdam",
                name: "Amsterdam",
                region: "Netherlands",
                priceFrom: 240,
                image: "images/image-5.png",
                description: "Canal-view suites for walkable weekends and remote-work resets.",
                collection: "city"
            },
            {
                id: "netherlands",
                name: "Netherlands",
                region: "Northwestern Europe",
                priceFrom: 265,
                image: "images/image-6.png",
                description: "Compact cities, design districts, and easy multi-stop itineraries.",
                collection: "city"
            },
            {
                id: "new-york",
                name: "New York",
                region: "United States",
                priceFrom: 360,
                image: "images/image-7.png",
                description: "Skyline-facing stays tuned for business trips and fast weekends.",
                collection: "city"
            },
            {
                id: "chicago",
                name: "Chicago",
                region: "United States",
                priceFrom: 280,
                image: "images/image-8.png",
                description: "Lakeside hotels, architecture tours, and polished boutique rooms.",
                collection: "city"
            },
            {
                id: "san-francisco",
                name: "San Francisco",
                region: "United States",
                priceFrom: 300,
                image: "images/image-9.png",
                description: "Tech-friendly apartments with strong Wi-Fi and neighborhood dining.",
                collection: "city"
            },
            {
                id: "shanghai",
                name: "Shanghai",
                region: "China",
                priceFrom: 330,
                image: "images/image-10.png",
                description: "High-rise stays and sleek hospitality for cosmopolitan trips.",
                collection: "signature"
            }
        ],
        hotspots: [
            {
                name: "Dubai",
                subtitle: "Skyline weekends",
                image: "images/dubai.png",
                collection: "signature"
            },
            {
                name: "New York",
                subtitle: "72-hour city energy",
                image: "images/new-york.png",
                collection: "city"
            },
            {
                name: "Paris",
                subtitle: "Gallery districts",
                image: "images/paris.png",
                collection: "city"
            },
            {
                name: "New Delhi",
                subtitle: "Layered cultural routes",
                image: "images/new-delhi.png",
                collection: "signature"
            }
        ],
        stories: [
            {
                name: "Ava & Julian",
                image: "images/story-1.png",
                title: "Booked a 4-day reset in Berlin",
                quote: "The new search flow let us filter by workspace, price, and style in one pass."
            },
            {
                name: "Mina",
                image: "images/story-2.png",
                title: "Moved a client trip in less than 10 minutes",
                quote: "Saved the shortlist, pushed the best stay to cart, and shared the final option instantly."
            },
            {
                name: "Omar & Leen",
                image: "images/story-3.png",
                title: "Turned a static plan into a real itinerary",
                quote: "Favorites, booking details, and profile settings finally behave like a real product."
            }
        ],
        socials: [
            { label: "Instagram", url: "https://instagram.com", key: "instagram" },
            { label: "X", url: "https://x.com", key: "x" },
            { label: "YouTube", url: "https://youtube.com", key: "youtube" },
            { label: "LinkedIn", url: "https://linkedin.com", key: "linkedin" }
        ],
        defaultProfile: {
            firstName: "Nadia",
            lastName: "Salem",
            email: "traveler@akatsuki.travel",
            phone: "+20 100 555 2026",
            homeAirport: "CAI",
            travelStyle: "Hybrid city and resort stays"
        },
        stays: [
            {
                slug: "berlin-loft",
                title: "Deluxe Queen Room With Street View",
                subtitle: "Appartement in Germany",
                location: "Berlin, Germany",
                country: "Germany",
                collection: "city",
                type: "Flat",
                price: 148,
                rating: 4.7,
                reviews: 312,
                guests: 2,
                beds: 1,
                baths: 1,
                image: "images/image-s1.png",
                gallery: ["images/image-s1.png", "images/house-2.png", "images/house-3.png", "images/house-4.png", "images/house-5.png"],
                amenities: ["Wifi", "Kitchen", "Air Conditioning", "Workspace"],
                badge: "Best for remote work",
                host: "Brandon",
                distance: "7 min to transit",
                description: "A bright loft with quiet street views, practical storage, and enough daylight to work or reset.",
                summary: "Made for short business trips and couples who want city access without the noise."
            },
            {
                slug: "sf-private-villa",
                title: "Private Villa With Sunset Terrace",
                subtitle: "Private Villa in San Francisco",
                location: "San Francisco, California",
                country: "United States",
                collection: "city",
                type: "Villa",
                price: 260,
                rating: 4.9,
                reviews: 208,
                guests: 4,
                beds: 2,
                baths: 2,
                image: "images/image-s2.png",
                gallery: ["images/image-s2.png", "images/house-1.png", "images/house-3.png", "images/house-4.png", "images/house-5.png"],
                amenities: ["Wifi", "Kitchen", "Pool", "Air Conditioning"],
                badge: "Sunset favorite",
                host: "Brandon",
                distance: "12 min to the waterfront",
                description: "A warmer, more private stay with terrace seating, layered lighting, and a guest-ready kitchen.",
                summary: "Ideal for longer weekends, couples trips, and travelers who want a premium residential feel."
            },
            {
                slug: "four-seasons-bay",
                title: "Harbor Club Room",
                subtitle: "Four Seasons Hotel",
                location: "San Francisco, California",
                country: "United States",
                collection: "city",
                type: "Hotel",
                price: 340,
                rating: 4.8,
                reviews: 418,
                guests: 2,
                beds: 1,
                baths: 1,
                image: "images/image-s3.png",
                gallery: ["images/image-s3.png", "images/house-1.png", "images/house-2.png", "images/house-4.png", "images/house-5.png"],
                amenities: ["Wifi", "Gym", "Pool", "Air Conditioning"],
                badge: "Hotel pick",
                host: "Brandon",
                distance: "Direct access to downtown",
                description: "A polished hotel room with concierge service, fast elevators, and a strong arrival experience.",
                summary: "Built for travelers who want premium service without sacrificing location."
            },
            {
                slug: "mission-guest-suite",
                title: "Modern Guest Suite Near Valencia",
                subtitle: "Appartement in San Francisco",
                location: "San Francisco, California",
                country: "United States",
                collection: "city",
                type: "Guest Suite",
                price: 190,
                rating: 4.6,
                reviews: 154,
                guests: 3,
                beds: 2,
                baths: 1,
                image: "images/image-s4.png",
                gallery: ["images/image-s4.png", "images/house-1.png", "images/house-2.png", "images/house-3.png", "images/house-5.png"],
                amenities: ["Wifi", "Kitchen", "Workspace"],
                badge: "Local favorite",
                host: "Brandon",
                distance: "Walkable food scene",
                description: "Compact, efficient, and styled for flexible travel with a stronger layout than the original build.",
                summary: "A smart choice for solo travelers or small groups who want value with personality."
            },
            {
                slug: "laguna-retreat",
                title: "Palm Court Villa With Private Pool",
                subtitle: "Private Villa in Laguna",
                location: "Laguna Beach, California",
                country: "United States",
                collection: "coast",
                type: "Villa",
                price: 385,
                rating: 4.9,
                reviews: 267,
                guests: 5,
                beds: 3,
                baths: 2,
                image: "images/image-s5.png",
                gallery: ["images/image-s5.png", "images/house-2.png", "images/house-3.png", "images/house-4.png", "images/house-5.png"],
                amenities: ["Wifi", "Kitchen", "Pool", "Air Conditioning"],
                badge: "Poolside reset",
                host: "Elena",
                distance: "4 min to the beach",
                description: "An airy villa with warm wood tones, pool access, and an easy indoor-outdoor rhythm.",
                summary: "Great for a slower coastal itinerary with enough room to settle in."
            },
            {
                slug: "capri-hotel",
                title: "Boutique Sea View Room",
                subtitle: "Cliffside Hotel in Capri",
                location: "Capri, Italy",
                country: "Italy",
                collection: "coast",
                type: "Hotel",
                price: 310,
                rating: 4.8,
                reviews: 198,
                guests: 2,
                beds: 1,
                baths: 1,
                image: "images/image-s6.png",
                gallery: ["images/image-s6.png", "images/house-1.png", "images/house-3.png", "images/house-4.png", "images/house-5.png"],
                amenities: ["Wifi", "Pool", "Air Conditioning", "Gym"],
                badge: "Sea view",
                host: "Elena",
                distance: "Cliffside terrace breakfast",
                description: "A boutique hotel room with layered blues, compact luxury, and direct sea-view moments.",
                summary: "Best for couples who want a resort feel with polished service."
            },
            {
                slug: "porto-flat",
                title: "Riverside Flat With Balcony",
                subtitle: "Design Flat in Porto",
                location: "Porto, Portugal",
                country: "Portugal",
                collection: "coast",
                type: "Flat",
                price: 172,
                rating: 4.7,
                reviews: 223,
                guests: 3,
                beds: 2,
                baths: 1,
                image: "images/image1.png",
                gallery: ["images/image1.png", "images/house-1.png", "images/house-2.png", "images/house-4.png", "images/house-5.png"],
                amenities: ["Wifi", "Kitchen", "Air Conditioning"],
                badge: "Budget smart",
                host: "Luis",
                distance: "Riverside walk access",
                description: "A compact coastal flat with balcony seating and a layout tuned for relaxed city-coast crossover trips.",
                summary: "Strong value for travelers who want to split time between cafes and waterfront walks."
            },
            {
                slug: "ibiza-house",
                title: "White House With Roof Deck",
                subtitle: "Mediterranean House in Ibiza",
                location: "Ibiza, Spain",
                country: "Spain",
                collection: "coast",
                type: "House",
                price: 295,
                rating: 4.8,
                reviews: 141,
                guests: 4,
                beds: 2,
                baths: 2,
                image: "images/image2.png",
                gallery: ["images/image2.png", "images/house-1.png", "images/house-2.png", "images/house-3.png", "images/house-5.png"],
                amenities: ["Wifi", "Kitchen", "Pool"],
                badge: "Weekend house",
                host: "Luis",
                distance: "8 min to beach clubs",
                description: "A bright whitewashed house with rooftop views, warm evenings, and strong group-trip appeal.",
                summary: "Easy for two couples or friends who want privacy without losing the social side of the island."
            },
            {
                slug: "alpine-chalet",
                title: "Woodland House Over The Valley",
                subtitle: "Chalet in Switzerland",
                location: "Zermatt, Switzerland",
                country: "Switzerland",
                collection: "signature",
                type: "House",
                price: 430,
                rating: 4.9,
                reviews: 176,
                guests: 6,
                beds: 3,
                baths: 2,
                image: "images/image7.png",
                gallery: ["images/image7.png", "images/house-2.png", "images/house-3.png", "images/house-4.png", "images/house-5.png"],
                amenities: ["Wifi", "Kitchen", "Workspace", "Air Conditioning"],
                badge: "Top-rated retreat",
                host: "Mika",
                distance: "Panorama valley view",
                description: "A dramatic chalet profile with layered seating zones and a view-first layout for slower stays.",
                summary: "Built for travelers who want the trip itself to feel elevated from the moment they arrive."
            },
            {
                slug: "desert-mirage-villa",
                title: "Mirage Villa With Dune Lounge",
                subtitle: "Private Villa in Dubai",
                location: "Dubai, United Arab Emirates",
                country: "United Arab Emirates",
                collection: "signature",
                type: "Villa",
                price: 480,
                rating: 4.9,
                reviews: 244,
                guests: 5,
                beds: 3,
                baths: 3,
                image: "images/image8.png",
                gallery: ["images/image8.png", "images/house-1.png", "images/house-3.png", "images/house-4.png", "images/house-5.png"],
                amenities: ["Wifi", "Kitchen", "Pool", "Gym"],
                badge: "Signature luxury",
                host: "Mika",
                distance: "Private transfer included",
                description: "High-contrast interiors, dedicated lounge zones, and a resort-grade outdoor setup.",
                summary: "A polished pick for premium leisure travel, celebrations, or design-led vacations."
            },
            {
                slug: "tokyo-loft",
                title: "Skyline Loft With Smart Controls",
                subtitle: "Future Loft in Tokyo",
                location: "Tokyo, Japan",
                country: "Japan",
                collection: "signature",
                type: "Flat",
                price: 275,
                rating: 4.8,
                reviews: 296,
                guests: 2,
                beds: 1,
                baths: 1,
                image: "images/image9.png",
                gallery: ["images/image9.png", "images/house-1.png", "images/house-2.png", "images/house-4.png", "images/house-5.png"],
                amenities: ["Wifi", "Kitchen", "Workspace", "Air Conditioning"],
                badge: "Smart stay",
                host: "Hiro",
                distance: "Direct metro line",
                description: "A compact signature loft with smart controls, dense functionality, and a stronger visual polish.",
                summary: "Best for travelers who like their stay to feel efficient, modern, and sharply detailed."
            },
            {
                slug: "santorini-suite",
                title: "Caldera Suite With Infinity Edge",
                subtitle: "Boutique Hotel in Santorini",
                location: "Santorini, Greece",
                country: "Greece",
                collection: "signature",
                type: "Hotel",
                price: 415,
                rating: 4.9,
                reviews: 188,
                guests: 2,
                beds: 1,
                baths: 1,
                image: "images/image10.png",
                gallery: ["images/image10.png", "images/house-1.png", "images/house-2.png", "images/house-3.png", "images/house-5.png"],
                amenities: ["Wifi", "Pool", "Air Conditioning"],
                badge: "Most saved",
                host: "Hiro",
                distance: "Sunset-facing terrace",
                description: "A high-demand suite with a clean silhouette, private plunge space, and panoramic sunset moments.",
                summary: "A classic special-occasion stay for couples who want impact without clutter."
            },
            {
                slug: "rainforest-glasshouse",
                title: "Glass House Over The Canopy",
                subtitle: "Rainforest House in Bali",
                location: "Ubud, Bali",
                country: "Indonesia",
                collection: "signature",
                type: "House",
                price: 365,
                rating: 4.8,
                reviews: 159,
                guests: 4,
                beds: 2,
                baths: 2,
                image: "images/image11.png",
                gallery: ["images/image11.png", "images/house-2.png", "images/house-3.png", "images/house-4.png", "images/house-5.png"],
                amenities: ["Wifi", "Pool", "Kitchen", "Workspace"],
                badge: "Nature reset",
                host: "Ayu",
                distance: "Jungle-facing deck",
                description: "A glass-heavy layout that opens into the landscape while still feeling controlled and calm.",
                summary: "Ideal for travelers who want a slower reset and a more cinematic place to stay."
            },
            {
                slug: "atlas-guest-suite",
                title: "Desert Guest Suite With Courtyard",
                subtitle: "Guest Suite in Marrakech",
                location: "Marrakech, Morocco",
                country: "Morocco",
                collection: "signature",
                type: "Guest Suite",
                price: 205,
                rating: 4.7,
                reviews: 207,
                guests: 3,
                beds: 2,
                baths: 1,
                image: "images/image12.png",
                gallery: ["images/image12.png", "images/house-1.png", "images/house-2.png", "images/house-3.png", "images/house-4.png"],
                amenities: ["Wifi", "Air Conditioning", "Kitchen"],
                badge: "Courtyard calm",
                host: "Ayu",
                distance: "5 min to the medina",
                description: "An intimate suite that blends warmer tones, privacy, and easy access to the old city.",
                summary: "Strong value for travelers who want character, location, and a quieter night setup."
            }
        ]
    };
})();
